source 'https://github.com/CocoaPods/Specs.git'

version = '10.0'
platform :ios, version

$isSourceCode = 0
$CarthagePodsPath = "./CarthagePods/"
target 'BuildStatcLibraryMixCathageCocoaPods' do

  if $isSourceCode ==  0
    pod 'AFNetworking', :path => $CarthagePodsPath + "AFNetworking"
    pod 'libwebp', :path => "./CarthagePods/libwebp"
    pod 'SDWebImageWebPCoder', :path => "./CarthagePods/SDWebImageWebPCoder"
    pod 'lottie-ios', :path => $CarthagePodsPath + "lottie-ios"
    pod 'FMDB', :path => $CarthagePodsPath + "FMDB"
    pod 'MarqueeLabel', :path => $CarthagePodsPath + "MarqueeLabel"
    pod 'YYText', :path => $CarthagePodsPath + "YYText"
    pod 'YYImage', :path => $CarthagePodsPath + "YYImage"
    pod 'MBProgressHUD', :path => $CarthagePodsPath + "MBProgressHUD"
    pod 'KVOController', :path => $CarthagePodsPath + "KVOController"
    pod 'SAMKeychain', :path => $CarthagePodsPath + "SAMKeychain"
    pod 'ZipArchive', :path => $CarthagePodsPath + "ZipArchive"
  else 
   pod 'AFNetworking', '4.0.1'
   pod 'SDWebImageWebPCoder', '0.8.1'
   pod 'lottie-ios', '3.1.8'
   pod 'FMDB', '2.7.5'
   pod 'MarqueeLabel', '4.0.2'
   pod 'YYText', '1.0.7'
   pod 'YYImage', '1.0.4'
   pod 'MBProgressHUD', '1.2.0'
   pod 'KVOController', '1.2.0'
   pod 'SAMKeychain', '1.5.3'
   pod 'SSZipArchive', '2.2.2'
  end
  
  pod 'IGListKit', '4.0.0'
  pod 'SDWebImage', '5.10.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < version.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = version
      end
    end
  end
end
